---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: travel-sample
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: travel-sample
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: travel-sample
    spec:
      containers:
      - name: travel-sample
        image: bauagonzo/cb-travel-sample:latest